name: LightEssentials
version: 1.0.0
main: net.australmc.lightessentials.LightEssentials

commands:
  feed:
    aliases: ['alimentar']
    description: "Fill the player's hunger status."
    permission: "lightessentials.feed"
    usage: '/<command> [playername]'